name: wine-ml-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - scikit-learn=1.3.0
  - pandas=2.1.0
  - numpy=1.26.0
  - joblib
  - locust
  - pip:
      # Azure ML v1 packages (still useful for logging, telemetry)
      - azureml-core
      - azureml-defaults
      - azureml-mlflow

      # Azure ML v2 SDK (needed for MLClient, Model)
      - azure-ai-ml>=1.0.0,<2.0
      - azure-identity>=1.15.0,<2.0

      # Visualization & drift detection
      - matplotlib>=3.8,<3.10
      - seaborn>=0.13,<0.14
      - scipy>=1.11,<2.0
